# Define the root logger with appender file
#log = /usr/home/log4j
#log4j.rootLogger = DEBUG, FILE

# Define the file appender
#log4j.appender.FILE=org.apache.log4j.RollingFileAppender
#log4j.appender.FILE.File=${log}/log.out
#log4j.appender.FILE.File=D:\\seleniumTestNGJava\\Logs\\Application.log
#log4j.appender.file.MaxFileSize=5000KB
#log4j.appender.file.MaxBackupIndex=1
# Define the layout for file appender
#log4j.appender.file.layout=org.apache.log4j.PatternLayout
#log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

#lof4j.appender.file.Append=false

#root logger
log4j.rootLogger = DEBUG, file
#appender
log4j.appender.file = org.apache.log4j.RollingFileAppender
log4j.appender.file.File = D:\\seleniumTestNGJava\\Logs\\firstoutput.log
log4j.appender.file.MaxFileSize = 2MB
log4j.appender.file.MaxBackupIndex = 3
#layout
log4j.appender.file.layout = org.apache.log4j.PatternLayout

